application: easyvoter-stanford
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /_ah/mail/.+
  script: votesimple.incomingmailapp
  login: admin
- url: /.*
  script: votesimple.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

inbound_services:
- mail



